// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnSz4FRpsFLfkXtSijx1Y1AH_UgIPFuwk',
    appId: '1:619459192919:web:a027d1a7732a09ec235b12',
    messagingSenderId: '619459192919',
    projectId: 'carbonari-sih',
    authDomain: 'carbonari-sih.firebaseapp.com',
    storageBucket: 'carbonari-sih.firebasestorage.app',
    measurementId: 'G-7DW4Q12WTP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdO8NiSLsJWnc0xuozGNhoJbI-CdpRYcA',
    appId: '1:619459192919:android:71bd4cec33a8081e235b12',
    messagingSenderId: '619459192919',
    projectId: 'carbonari-sih',
    storageBucket: 'carbonari-sih.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_MJ_3_cj00-fZ8apC_bqR4CWQIcb4-sc',
    appId: '1:619459192919:ios:21f567bfd1ebbb91235b12',
    messagingSenderId: '619459192919',
    projectId: 'carbonari-sih',
    storageBucket: 'carbonari-sih.firebasestorage.app',
    iosBundleId: 'com.example.civicReporter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_MJ_3_cj00-fZ8apC_bqR4CWQIcb4-sc',
    appId: '1:619459192919:ios:21f567bfd1ebbb91235b12',
    messagingSenderId: '619459192919',
    projectId: 'carbonari-sih',
    storageBucket: 'carbonari-sih.firebasestorage.app',
    iosBundleId: 'com.example.civicReporter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnSz4FRpsFLfkXtSijx1Y1AH_UgIPFuwk',
    appId: '1:619459192919:web:ad3c237b55aa120a235b12',
    messagingSenderId: '619459192919',
    projectId: 'carbonari-sih',
    authDomain: 'carbonari-sih.firebaseapp.com',
    storageBucket: 'carbonari-sih.firebasestorage.app',
    measurementId: 'G-FCMSKTL3HW',
  );
}
